/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.harvard;

import static java.lang.System.exit;

import java.io.IOException;

import io.grpc.Grpc;
import io.grpc.InsecureServerCredentials;
import io.grpc.Server;
import io.grpc.Status;
import io.grpc.stub.StreamObserver;
import edu.harvard.Chat.AccountLookupRequest;
import edu.harvard.Chat.AccountLookupResponse;
import edu.harvard.Chat.DeleteAccountRequest;
import edu.harvard.Chat.DeleteMessagesRequest;
import edu.harvard.Chat.ListAccountsRequest;
import edu.harvard.Chat.ListAccountsResponse;
import edu.harvard.Chat.LoginCreateRequest;
import edu.harvard.Chat.LoginCreateResponse;
import edu.harvard.Chat.RequestMessagesRequest;
import edu.harvard.Chat.RequestMessagesResponse;
import edu.harvard.Chat.SendMessageRequest;
import edu.harvard.Chat.SendMessageResponse;
import edu.harvard.logic.Configuration;
import edu.harvard.logic.Database;
import edu.harvard.logic.OperationHandler;
import edu.harvard.logic.OperationHandler.HandleException;
import edu.harvard.Chat.Empty;

public class App {
	public static void main(String[] args) {
		Configuration config;
		try {
			config = new Configuration("../".concat(args.length > 0 ? args[0] : "config.json"));
		} catch (IOException ex) {
			System.err.println("Loading configuration failed!");
			System.err.println(ex);
			exit(1);
			return;
		}
		try {
			String port = config.clientPort;
			startServer(Integer.parseInt(port));
		} catch (IOException ex) {
			System.err.println("Unhandled I/O failure!");
			System.err.println(ex.getMessage());
			for (StackTraceElement ste : ex.getStackTrace()) {
				System.err.println(ste + "\n");
			}
		}
	}

	public static void startServer(int port) throws IOException {
		Database db = new Database();
		Server server = Grpc.newServerBuilderForPort(port, InsecureServerCredentials.create())
				.addService(new ChatService(db)).build();
		server.start();
		try {
			System.out.println("Running!");
			server.awaitTermination();
		} catch (InterruptedException ex) {
			System.exit(0);
		}
	}

	private static class ChatService extends ChatServiceGrpc.ChatServiceImplBase {
		private final OperationHandler handler;

		ChatService(Database db) {
			this.handler = new OperationHandler(db);
		}

		@Override
		public void accountLookup(AccountLookupRequest request, StreamObserver<AccountLookupResponse> response) {
			AccountLookupResponse lookupResponse = handler.lookupAccount(request.getUsername());
			response.onNext(lookupResponse);
			response.onCompleted();
		}

		@Override
		public void login(LoginCreateRequest request, StreamObserver<LoginCreateResponse> response) {
			LoginCreateResponse loginResponse = handler.login(request);
			response.onNext(loginResponse);
			response.onCompleted();
		}

		@Override
		public void createAccount(LoginCreateRequest request, StreamObserver<LoginCreateResponse> response) {
			try {
				LoginCreateResponse createResponse = handler.createAccount(request);
				response.onNext(createResponse);
				response.onCompleted();
			} catch (HandleException e) {
				Status status = Status.INVALID_ARGUMENT.withDescription(e.getMessage());
				response.onError(status.asRuntimeException());
			}
		}

		@Override
		public void listAccounts(ListAccountsRequest request, StreamObserver<ListAccountsResponse> response) {
			String id = handler.lookupSession(request.getSessionKey());
			if (id == null) {
				Status status = Status.UNAUTHENTICATED.withDescription("Invalid session key");
				response.onError(status.asRuntimeException());
			} else {
				ListAccountsResponse listResponse = handler.listAccounts(request);
				response.onNext(listResponse);
				response.onCompleted();
			}
		}

		@Override
		public void sendMessage(SendMessageRequest request, StreamObserver<SendMessageResponse> response) {
			String user_id = handler.lookupSession(request.getSessionKey());
			if (user_id == null) {
				Status status = Status.UNAUTHENTICATED.withDescription("Invalid session key");
				response.onError(status.asRuntimeException());
			} else {
				try {
					String message_id = handler.sendMessage(user_id, request);
					response.onNext(SendMessageResponse.newBuilder().setId(message_id).build());
					response.onCompleted();
				} catch (HandleException e) {
					Status status = Status.INVALID_ARGUMENT.withDescription(e.getMessage());
					response.onError(status.asRuntimeException());
				}
			}
		}

		@Override
		public void requestMessages(RequestMessagesRequest request, StreamObserver<RequestMessagesResponse> response) {
			String id = handler.lookupSession(request.getSessionKey());
			if (id == null) {
				Status status = Status.UNAUTHENTICATED.withDescription("Invalid session key");
				response.onError(status.asRuntimeException());
			} else {
				RequestMessagesResponse messagesResponse = handler.requestMessages(id, request.getMaximumNumber());
				response.onNext(messagesResponse);
				response.onCompleted();
			}
		}

		@Override
		public void deleteMessages(DeleteMessagesRequest request, StreamObserver<Empty> response) {
			String id = handler.lookupSession(request.getSessionKey());
			if (id == null) {
				Status status = Status.UNAUTHENTICATED.withDescription("Invalid session key");
				response.onError(status.asRuntimeException());
			} else {
				handler.deleteMessages(id, request.getIdList());
				response.onNext(Empty.newBuilder().build());
				response.onCompleted();
			}
		}

		@Override
		public void deleteAccount(DeleteAccountRequest request, StreamObserver<Empty> response) {
			String id = handler.lookupSession(request.getSessionKey());
			if (id == null) {
				Status status = Status.UNAUTHENTICATED.withDescription("Invalid session key");
				response.onError(status.asRuntimeException());
			} else {
				handler.deleteAccount(id);
				response.onNext(Empty.newBuilder().build());
				response.onCompleted();
			}
		}
	}
}
